exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-comprehensions
      - flake8-logging-format
      - flake8-builtins
      - flake8-eradicate
      - pep8-naming
      - flake8-pytest
      - flake8-docstrings
      - flake8-rst-docstrings
      - flake8-rst
      - flake8-copyright
      - flake8-ownership
      - flake8-markdown
      - flake8-bugbear
      - flake8-comprehensions
      - flake8-print


- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.2
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.8.0
  hooks:
    - id: rst-backticks

- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.4
  hooks:
  -   id: pyupgrade
