name: Run Demo
on: [push, pull_request]


jobs:
  tests:
    name: Run Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      ENV_NAME: testing
    strategy:
      fail-fast: false
      matrix:
        demo: ["getting_started", "understanding_21cmsense", "reproducing_pober_2015"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Test Deps
        run: |
          uv sync --all-extras --dev

      - name: Install ska-ost-array
        run: |
          git clone https://gitlab.com/ska-telescope/ost/ska-ost-array-config.git
          cd ska-ost-array-config
          uv pip install .
          cd ..

      - name: Install ipykernel
        run: |
          uv run python -m ipykernel install --user --name sense --display-name "sense"

      - name: Run Notebook
        run: |
          uv run papermill -k sense docs/tutorials/${{ matrix.demo }}.ipynb output-${{ matrix.demo }}.ipynb

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: ${{ matrix.demo }}
          path: output-${{ matrix.demo }}.ipynb
