name: Run Demo
on: [push, pull_request]


jobs:
  tests:
    name: Run Demo
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      ENV_NAME: testing
    strategy:
      fail-fast: false
      matrix:
        demo: ["getting_started", "understanding_21cmsense", "reproducing_pober_2015"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.3
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: "3.10"
          environment-file: ci/${{ env.ENV_NAME }}.yaml
          activate-environment: ${{ env.ENV_NAME }}

      - name: Conda Info
        run: |
          conda info
          python --version

      - name: Install Deps
        run: |
          pip install .
          pip install papermill ipykernel
          conda list

      - name: Install ipykernel
        run: python -m ipykernel install --user --name sense --display-name "sense"

      - name: Run Notebook
        run: |
          papermill -k sense docs/tutorials/${{ matrix.demo }}.ipynb output-${{ matrix.demo }}.ipynb

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.demo }}
          path: output-${{ matrix.demo }}.ipynb
