name: Test Suite
on: [push, pull_request]


jobs:
  tests:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Test Deps
        run: |
          uv pip install --system .[test]
          uv pip list --system

      - name: Install ska-ost-array-config
        run: |
          uv pip install --system \
            --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple/ \
            "ska-ost-array-config>=5"

      - name: Run Tests
        run: |
          python -m pytest --cov=py21cmsense --cov-config=.coveragerc --cov-report xml:./coverage.xml

      - uses: codecov/codecov-action@v7
        if: success()
        with:
          file: ./coverage.xml #optional
          token: ${{ secrets.CODECOV_TOKEN }} #required
