name: Warnings Test
on: [pull_request]


jobs:
  tests:
    name: Test With Warnings
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Test Deps
        run: |
          uv pip install --system .[test]
          uv pip list --system

      - name: Run Tests
        run: |
          python -m pytest -W error
