name: Warnings Test
on: [pull_request]


jobs:
  tests:
    name: Test With Warnings
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Test Deps
        run: |
          uv sync --all-extras --dev

      - name: Run Tests
        run: |
          uv run pytest -W error
